// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/v1/documents/process": {
            "post": {
                "description": "Submit a document for async processing. Returns job_id for polling.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "summary": "Process a document",
                "parameters": [
                    {
                        "description": "Document processing request",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/textflow_internal_models.CreateJobRequest"
                        }
                    }
                ],
                "responses": {
                    "202": {
                        "description": "Accepted",
                        "schema": {
                            "$ref": "#/definitions/textflow_internal_models.CreateJobResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/textflow_internal_models.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/textflow_internal_models.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/v1/documents/upload": {
            "post": {
                "description": "Upload a document via multipart/form-data for async processing.",
                "consumes": [
                    "multipart/form-data"
                ],
                "produces": [
                    "application/json"
                ],
                "summary": "Upload a document",
                "parameters": [
                    {
                        "type": "file",
                        "description": "Document file",
                        "name": "file",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Filename",
                        "name": "filename",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "description": "Webhook URL for completion notification",
                        "name": "notify_webhook",
                        "in": "formData"
                    }
                ],
                "responses": {
                    "202": {
                        "description": "Accepted",
                        "schema": {
                            "$ref": "#/definitions/textflow_internal_models.CreateJobResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/textflow_internal_models.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/v1/documents/{id}": {
            "get": {
                "description": "Returns job status and current pipeline step. Does not include results — use /download for results.",
                "produces": [
                    "application/json"
                ],
                "summary": "Get job status",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Job ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Job status with current_step field",
                        "schema": {
                            "$ref": "#/definitions/textflow_internal_models.GetJobResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/textflow_internal_models.ErrorResponse"
                        }
                    }
                }
            },
            "delete": {
                "description": "Remove a completed or failed job and its associated data.",
                "summary": "Delete a job",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Job ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/textflow_internal_models.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/v1/documents/{id}/download": {
            "get": {
                "description": "Returns gzip-compressed JSON results from filesystem. Only available when job status is completed.",
                "produces": [
                    "application/json"
                ],
                "summary": "Download job results",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Job ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Compression type (gzip)",
                        "name": "compression",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Gzip-compressed JSON (Content-Encoding: gzip)",
                        "schema": {
                            "$ref": "#/definitions/textflow_internal_models.JobResults"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/textflow_internal_models.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/v1/documents/{id}/entities": {
            "get": {
                "description": "Returns a flat list of all entities extracted from the document.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "documents"
                ],
                "summary": "Get document entities",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Job ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/cmd_orchestrator_handlers.EntitiesResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/textflow_internal_models.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/textflow_internal_models.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/v1/documents/{id}/graph": {
            "get": {
                "description": "Returns nodes and edges representing the document structure for graph database ingestion.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "documents"
                ],
                "summary": "Get document graph",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Job ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/cmd_orchestrator_handlers.GraphResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/textflow_internal_models.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/textflow_internal_models.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/v1/documents/{id}/inferences": {
            "get": {
                "description": "Returns a flat list of all inferences with resolved entity_id_refs for knowledge graph construction.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "documents"
                ],
                "summary": "Get document inferences",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Job ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "Page number (default: 1)",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Items per page (default: 100)",
                        "name": "limit",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/cmd_orchestrator_handlers.InferencesResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/textflow_internal_models.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/textflow_internal_models.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/v1/documents/{id}/vectors": {
            "get": {
                "description": "Returns chunks and inferences with optional embeddings for vector database ingestion.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "documents"
                ],
                "summary": "Get document vectors",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Job ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "boolean",
                        "description": "Include embeddings (default: true)",
                        "name": "embeddings",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Comma-separated fields to include (chunks,inferences)",
                        "name": "fields",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Page number (default: 1)",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Items per page (default: 100)",
                        "name": "limit",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/cmd_orchestrator_handlers.VectorsResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/textflow_internal_models.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/textflow_internal_models.ErrorResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "cmd_orchestrator_handlers.ChunkVector": {
            "type": "object",
            "properties": {
                "chunk_id": {
                    "type": "string"
                },
                "embedding": {
                    "type": "array",
                    "items": {
                        "type": "number"
                    }
                },
                "text": {
                    "type": "string"
                }
            }
        },
        "cmd_orchestrator_handlers.Edge": {
            "type": "object",
            "properties": {
                "from": {
                    "type": "string"
                },
                "to": {
                    "type": "string"
                },
                "type": {
                    "type": "string"
                }
            }
        },
        "cmd_orchestrator_handlers.EntitiesResponse": {
            "type": "object",
            "properties": {
                "entities": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/cmd_orchestrator_handlers.EntityFlat"
                    }
                },
                "job_id": {
                    "type": "string"
                },
                "schema_version": {
                    "type": "string"
                }
            }
        },
        "cmd_orchestrator_handlers.EntityFlat": {
            "type": "object",
            "properties": {
                "confidence": {
                    "type": "number"
                },
                "entity_id": {
                    "type": "string"
                },
                "label": {
                    "type": "string"
                },
                "text": {
                    "type": "string"
                }
            }
        },
        "cmd_orchestrator_handlers.GraphResponse": {
            "type": "object",
            "properties": {
                "edges": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/cmd_orchestrator_handlers.Edge"
                    }
                },
                "job_id": {
                    "type": "string"
                },
                "nodes": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/cmd_orchestrator_handlers.Node"
                    }
                },
                "schema_version": {
                    "type": "string"
                }
            }
        },
        "cmd_orchestrator_handlers.InferenceFlat": {
            "type": "object",
            "properties": {
                "chunk_id": {
                    "type": "string"
                },
                "confidence": {
                    "type": "number"
                },
                "entity_id_refs": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "entity_refs": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "inference_id": {
                    "type": "string"
                },
                "text": {
                    "type": "string"
                }
            }
        },
        "cmd_orchestrator_handlers.InferenceVector": {
            "type": "object",
            "properties": {
                "chunk_id": {
                    "type": "string"
                },
                "embedding": {
                    "type": "array",
                    "items": {
                        "type": "number"
                    }
                },
                "inference_id": {
                    "type": "string"
                },
                "text": {
                    "type": "string"
                }
            }
        },
        "cmd_orchestrator_handlers.InferencesResponse": {
            "type": "object",
            "properties": {
                "inferences": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/cmd_orchestrator_handlers.InferenceFlat"
                    }
                },
                "job_id": {
                    "type": "string"
                },
                "schema_version": {
                    "type": "string"
                }
            }
        },
        "cmd_orchestrator_handlers.Node": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "string"
                },
                "label": {
                    "type": "string"
                },
                "props": {
                    "type": "object",
                    "additionalProperties": {}
                }
            }
        },
        "cmd_orchestrator_handlers.VectorsResponse": {
            "type": "object",
            "properties": {
                "chunks": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/cmd_orchestrator_handlers.ChunkVector"
                    }
                },
                "inferences": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/cmd_orchestrator_handlers.InferenceVector"
                    }
                },
                "job_id": {
                    "type": "string"
                },
                "schema_version": {
                    "type": "string"
                }
            }
        },
        "textflow_internal_models.Chunk": {
            "type": "object",
            "properties": {
                "chunk_id": {
                    "type": "string"
                },
                "embeddings": {
                    "type": "array",
                    "items": {
                        "type": "number"
                    }
                },
                "end_offset": {
                    "type": "integer"
                },
                "entity_ids": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "inferences": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/textflow_internal_models.InferenceItem"
                    }
                },
                "start_offset": {
                    "type": "integer"
                },
                "text": {
                    "type": "string"
                },
                "token_count": {
                    "type": "integer"
                }
            }
        },
        "textflow_internal_models.CreateJobRequest": {
            "type": "object",
            "properties": {
                "document_base64": {
                    "type": "string"
                },
                "document_url": {
                    "type": "string"
                },
                "features": {
                    "description": "e.g. [\"inferences\"]",
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "filename": {
                    "type": "string"
                },
                "webhook_secret": {
                    "type": "string"
                },
                "webhook_url": {
                    "type": "string"
                }
            }
        },
        "textflow_internal_models.CreateJobResponse": {
            "type": "object",
            "properties": {
                "job_id": {
                    "type": "string"
                },
                "status": {
                    "$ref": "#/definitions/textflow_internal_models.JobStatus"
                },
                "status_url": {
                    "type": "string"
                }
            }
        },
        "textflow_internal_models.EntityMinimal": {
            "type": "object",
            "properties": {
                "chunk_id": {
                    "type": "string"
                },
                "confidence": {
                    "type": "number"
                },
                "end_offset": {
                    "type": "integer"
                },
                "label": {
                    "type": "string"
                },
                "start_offset": {
                    "type": "integer"
                },
                "text": {
                    "type": "string"
                }
            }
        },
        "textflow_internal_models.ErrorResponse": {
            "type": "object",
            "properties": {
                "detail": {
                    "type": "string"
                },
                "error": {
                    "type": "string"
                }
            }
        },
        "textflow_internal_models.GetJobResponse": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string"
                },
                "current_step": {
                    "type": "string"
                },
                "error": {
                    "type": "string"
                },
                "job_id": {
                    "type": "string"
                },
                "status": {
                    "$ref": "#/definitions/textflow_internal_models.JobStatus"
                },
                "steps": {
                    "type": "object",
                    "additionalProperties": {
                        "type": "string"
                    }
                }
            }
        },
        "textflow_internal_models.InferenceItem": {
            "type": "object",
            "properties": {
                "confidence": {
                    "type": "number"
                },
                "embedding": {
                    "type": "array",
                    "items": {
                        "type": "number"
                    }
                },
                "entity_id": {
                    "type": "string"
                },
                "entity_id_refs": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "entity_refs": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "text": {
                    "type": "string"
                }
            }
        },
        "textflow_internal_models.JobResults": {
            "type": "object",
            "properties": {
                "chunks": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/textflow_internal_models.Chunk"
                    }
                },
                "completed_at": {
                    "type": "string"
                },
                "created_at": {
                    "type": "string"
                },
                "document_metadata": {
                    "type": "object",
                    "additionalProperties": true
                },
                "entities": {
                    "type": "object",
                    "additionalProperties": {
                        "$ref": "#/definitions/textflow_internal_models.EntityMinimal"
                    }
                },
                "job_id": {
                    "type": "string"
                },
                "schema_version": {
                    "type": "string"
                },
                "source_classification": {
                    "$ref": "#/definitions/textflow_internal_models.SourceClassificationResult"
                },
                "status": {
                    "type": "string"
                },
                "text": {
                    "type": "string"
                },
                "text_metadata": {
                    "type": "object",
                    "additionalProperties": true
                }
            }
        },
        "textflow_internal_models.JobStatus": {
            "type": "string",
            "enum": [
                "pending",
                "extracting",
                "processing",
                "embedding",
                "entities",
                "inferences",
                "transcribing",
                "analyzing_image",
                "completed",
                "failed"
            ],
            "x-enum-varnames": [
                "StatusPending",
                "StatusExtracting",
                "StatusProcessing",
                "StatusEmbedding",
                "StatusEntities",
                "StatusInferences",
                "StatusTranscribing",
                "StatusAnalyzingImage",
                "StatusCompleted",
                "StatusFailed"
            ]
        },
        "textflow_internal_models.SourceClassificationResult": {
            "type": "object",
            "properties": {
                "classifier_version": {
                    "type": "string"
                },
                "confidence": {
                    "type": "number"
                },
                "document_type": {
                    "description": "e.g. \"notariado\", \"catastro\", \"bancario\"",
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "",
	Description:      "",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
